const mongoose = require( 'mongoose' );
const Schema = mongoose.Schema;
//Crear esquema de la base de datos
let InformeSchema= new Schema ({
    
    orden: { type:String },
    planta: { type: String },
    cliente: { type: String },
    container: { type: String },
    motonave: {  type: String  },
    inporter: { type: String },
    portDest: {  type: String },
    portOrig: { type: String },
    espices: { type: String },
    patenteCamion: { type: String } ,
    patenteCarro: { type: String },
    booking: { type: String },
    empresaTrasnporte: { type: String },
    cantPallets: { type: Number },
    horaCarga: { type: Date },
    termografo1: { type: String },
    termografo2: { type: String },
    termografoPallet1: { type: String },
    termografoPallet2: { type: String },
    cantCajas: { type: Number },
    limpio: { type: Boolean },
    preEnfriado: { type: Boolean },
    buenEstado: { type: Boolean },
    tipoCarga: { type: String},
    seteoContainer: { type: Number },
    ventilacion: { type: Number },
    pti: { type: Date},
    anoContainer: {type: Date},
    admosferaNumero: {tyoe: Number},
    admosferaPorcentaje: {type: Number},
    quest: {type: Number},
    coments: { type: String},
    a1: {type: String}, ta1: {type: Number}, b1: {type: String}, tb1: {type: String},
    a2: {type: String}, ta2: {type: Number}, b2: {type: String}, tb2: {type: String},
    a3: {type: String}, ta3: {type: Number}, b3: {type: String}, tb3: {type: String},
    a4: {type: String}, ta4: {type: Number}, b4: {type: String}, tb4: {type: String},
    a5: {type: String}, ta5: {type: Number}, b5: {type: String}, tb5: {type: String},
    a6: {type: String}, ta6: {type: Number}, b6: {type: String}, tb6: {type: String},
    a7: {type: String}, ta7: {type: Number}, b7: {type: String}, tb7: {type: String},
    a8: {type: String}, ta8: {type: Number}, b8: {type: String}, tb8: {type: String},
    a9: {type: String}, ta9: {type: Number}, b9: {type: String}, tb9: {type: String},
    a10: {type: String}, ta10: {type: Number}, b10: {type: String}, tb10: {type: String},
});
//esportar el model Informe con el esquema definido
module.exports = mongoose.model('Informe', InformeSchema);
